services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=123123
      - MINIO_ACCESS_KEY=Xoor6735OhqmskqwOQMK
      - MINIO_SECRET_KEY=GzpUaz5KpgZ7FZxck0eixcOYfCvVWPTzQEbhod04
      - MINIO_ENDPOINT=172.21.0.4:9000
      - MINIO_EXTERNAL_ENDPOINT=127.0.0.1:9000
      - MINIO_BUCKET=test
      - MINIO_REGION=eu-west-1
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      - redis
      - minio

  database:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.0-alpine
    hostname: redis

  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./frontend
        target: /srv/app
      - /srv/app/node_modules
    environment:
      - API_URL=localhost:8000
    tty: true
    command: >
      sh -c "npm run dev"
    depends_on:
      - backend

  minio:
    image: minio/minio
    command: server /data --console-address ":9090"
    ports:
      - 9090:9090
      - 9000:9000
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=TestPassword
    restart: unless-stopped

volumes:
  pgdata:
