# Generated by Django 4.2.4 on 2023-09-10 08:13

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_storage.folder')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='cloud_storage.cloudstorage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
