# Generated by Django 4.2.4 on 2024-01-13 12:49

import cloud_storage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import mptt.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstorage',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_storage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('size', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent_folder', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cloud_storage.folder')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='cloud_storage.cloudstorage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='test'), upload_to=cloud_storage.models.get_file_path)),
                ('is_public', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud_storage.folder')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud_storage.cloudstorage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
