# Generated by Django 4.2.4 on 2023-09-11 15:50

import cloud_storage.models
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0004_alter_folder_id_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='test'), upload_to=cloud_storage.models.get_file_path)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud_storage.folder')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud_storage.cloudstorage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
