# Generated by Django 4.2.4 on 2023-09-08 15:59

from django.db import migrations, models
import django_minio_backend.models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(storage=django_minio_backend.models.MinioBackend(bucket_name='test'), upload_to=users.models.user_avatar_path, verbose_name='User Avatar'),
        ),
    ]
